var data = [
    { id: 0, name: "Qui-Gon Jinn", skip: false },
    { id: 1, name: "Obi-Wan Kenobi (Jedi Master)", skip: false },
    { id: 2, name: "Luke Skywalker (Hoth)", skip: false },
    { id: 3, name: "Ugnaught", skip: false },
    { id: 4, name: "Ewok", skip: false },
    { id: 5, name: "Imperial Guard", skip: false },
    { id: 6, name: "Admiral Ackbar", skip: false },
    { id: 7, name: "Anakin Skywalker (Ghost)", skip: false },
    { id: 8, name: "Luke Skywalker (Pilot)", skip: false },
    { id: 9, name: "Luke Skywalker (Dagobah)", skip: false },
    { id: 10, name: "Luke Skywalker (Jedi)", skip: false },
    { id: 11, name: "Han Solo (Skiff)", skip: false },
    { id: 12, name: "Rebel Pilot", skip: false },
    { id: 13, name: "Snowtrooper", skip: false },
    { id: 14, name: "Lobot", skip: false },
    { id: 15, name: "Bespin Guard", skip: false },
    { id: 16, name: "The Emperor", skip: false },
    { id: 17, name: "IG-88", skip: false },
    { id: 18, name: "Ben Kenobi (Ghost)", skip: false },
    { id: 19, name: "Yoda (Ghost)", skip: false },
    { id: 20, name: "Luke Skywalker (Bespin)", skip: false },
    { id: 21, name: "Princess Leia (Bespin)", skip: false },
    { id: 22, name: "Jar Jar Binks", skip: false },
    { id: 23, name: "Princess Leia (Slave)", skip: false },
    { id: 24, name: "Princess Leia (Prisoner)", skip: false },
    { id: 25, name: "Bib Fortuna", skip: false },
    { id: 26, name: "Palace Guard", skip: false },
    { id: 27, name: "Skiff Guard", skip: false },
    { id: 28, name: "Dengar", skip: false },
    { id: 29, name: "4-LOM", skip: false },
    { id: 30, name: "R2-Q5", skip: false },
    { id: 31, name: "Gungan Warrior", skip: false },
    { id: 32, name: "Lando Calrissian", skip: false },
    { id: 33, name: "Princess Leia (Boushh)", skip: false },
    { id: 34, name: "Princess Leia (Endor)", skip: false },
    { id: 35, name: "Wicket", skip: false },
    { id: 36, name: "Gamorrean Guard", skip: false },
    { id: 37, name: "R4-P17", skip: false },
    { id: 38, name: "Bossk", skip: false },
    { id: 39, name: "Boba Fett", skip: false },
    { id: 40, name: "Anakin Skywalker (Padawan)", skip: false },
    { id: 41, name: "Indiania Jones", skip: false },
    { id: 42, name: "STRANGER 1", skip: false },
    { id: 43, name: "Womp Rat", skip: false },
    { id: 44, name: "Lando (Palace Guard)", skip: false },
    { id: 45, name: "Luke Skywalker (Endor)", skip: false },
    { id: 46, name: "Darth Vader", skip: false },
    { id: 47, name: "Queen Amidala", skip: false },
    { id: 48, name: "Princess Leia (Boushh)", skip: false },
    { id: 49, name: "Unknown", skip: false },
    { id: 50, name: "Rancor", skip: false },
    { id: 51, name: "ASP Droid", skip: false },
    { id: 52, name: "R1-G4", skip: false },
    { id: 53, name: "Chancellor Palpatine", skip: false },
    { id: 54, name: "Chewbacca", skip: false },
    { id: 55, name: "Ben Kenobi", skip: false },
    { id: 56, name: "Han Solo (Endor)", skip: false },
    { id: 57, name: "Gonk Droid", skip: false },
    { id: 58, name: "Battle Droid (Security)", skip: false },
    { id: 59, name: "Droideka", skip: false },
    { id: 60, name: "Scout Trooper", skip: false },
    { id: 61, name: "Padmé (Geonosis) / Padmé (Clawed)", skip: false },
    { id: 62, name: "Droid 2", skip: false },
    { id: 63, name: "Mace Windu", skip: false },
    { id: 64, name: "Obi-Wan Kenobi (Episode III)", skip: false },
    { id: 65, name: "Princess Leia", skip: false },
    { id: 66, name: "Captain Antilles", skip: false },
    { id: 67, name: "Han Solo (Stormtrooper)", skip: false },
    { id: 68, name: "PK Droid", skip: false },
    { id: 69, name: "Battle Droid", skip: false },
    { id: 70, name: "Captain Tarpals", skip: false },
    { id: 71, name: "Pit Droid", skip: false },
    { id: 72, name: "Wampa", skip: false },
    { id: 73, name: "Buzz Droid", skip: false },
    { id: 74, name: "", skip: false },
    { id: 75, name: "Anakin Skywalker (Jedi)", skip: false },
    { id: 76, name: "Obi-Wan Kenobi", skip: false },
    { id: 77, name: "Rebel Friend", skip: false },
    { id: 78, name: "Luke Skywalker (Stormtrooper)", skip: false },
    { id: 79, name: "TC-14", skip: false },
    { id: 80, name: "Battle Droid (Commander)", skip: false },
    { id: 81, name: "Boss Nass", skip: false },
    { id: 82, name: "Watto", skip: false },
    { id: 83, name: "Zam Wesell", skip: false },
    { id: 84, name: "Treadwell Droid", skip: false },
    { id: 85, name: "C-3PO", skip: false },
    { id: 86, name: "Yoda", skip: false },
    { id: 87, name: "Commander Cody", skip: false },
    { id: 88, name: "Luke Skywalker (Tatooine)", skip: false },
    { id: 89, name: "Han Solo", skip: false },
    { id: 90, name: "Han Solo (Hoth)", skip: false },
    { id: 91, name: "Princess Leia (Hoth)", skip: false },
    { id: 92, name: "Royal Guard", skip: false },
    { id: 93, name: "Padmé", skip: false },
    { id: 94, name: "Darth Maul", skip: false },
    { id: 95, name: "Captain Panaka", skip: false },
    { id: 96, name: "Dexter Jettster", skip: false },
    { id: 97, name: "Clone", skip: false },
    { id: 98, name: "Geonosian", skip: false },
    { id: 99, name: "Super Battle Droid", skip: false },
    { id: 100, name: "Padmé (Battl", skip: false },
    { id: 101, name: "Aayla Secura", skip: false },
    { id: 102, name: "R2-D2", skip: false },
    { id: 103, name: "Clone (Episode III, Pilot)", skip: false },
    { id: 104, name: "Imperial Shuttle Pilot", skip: false },
    { id: 105, name: "Sandtrooper", skip: false },
    { id: 106, name: "Imperial Spy", skip: false },
    { id: 107, name: "Han Solo (Hood)", skip: false },
    { id: 108, name: "Lama Su", skip: false },
    { id: 109, name: "Battle Droid (Geonosis)", skip: false },
    { id: 110, name: "Boba Fett (Boy)", skip: false },
    { id: 111, name: "Ki-Adi Mundi", skip: false },
    { id: 112, name: "Plo Koon", skip: false },
    { id: 113, name: "General Grievous", skip: false },
    { id: 114, name: "Clone (Episode III, Swamp)", skip: false },
    { id: 115, name: "Disguised Clone", skip: false },
    { id: 116, name: "Tusken Raider", skip: false },
    { id: 117, name: "Beach Trooper", skip: false },
    { id: 118, name: "Imperial Officer", skip: false },
    { id: 120, name: "Taun We", skip: false },
    { id: 121, name: "Luminara", skip: false },
    { id: 122, name: "Kit Fisto", skip: false },
    { id: 123, name: "Count Dooku", skip: false },
    { id: 124, name: "Wookiee", skip: false },
    { id: 125, name: "Clone (Episode III, Walker)", skip: false },
    { id: 126, name: "Rebel Trooper", skip: false },
    { id: 127, name: "Jawa", skip: false },
    { id: 128, name: "Death Star Trooper", skip: false },
    { id: 129, name: "Grand Moff Tarkin", skip: false },
    { id: 132, name: "Jango Fett", skip: false },
    { id: 133, name: "Shaak Ti", skip: false },
    { id: 134, name: "Grievous' Bodyguard", skip: false },
    { id: 135, name: "Clone (Episode III)", skip: false },
    { id: 136, name: "Mace Windu (Episode III)", skip: false },
    { id: 137, name: "Stormtrooper", skip: false },
    { id: 138, name: "Anakin Skywalker (Boy)", skip: false },
    { id: 139, name: "Greedo", skip: false },
    { id: 140, name: "TIE Fighter Pilot", skip: false },
    { id: 141, name: "Rebel Trooper (Hoth)", skip: false }
];
