var data = [
    { id: 0, name: "Qui-Gon Jinn" },
    { id: 1, name: "Obi-Wan Kenobi (Jedi Master)" },
    { id: 2, name: "Luke Skywalker (Hoth)" },
    { id: 3, name: "Ugnaught" },
    { id: 4, name: "Ewok" },
    { id: 5, name: "Imperial Guard" },
    { id: 6, name: "Admiral Ackbar" },
    { id: 7, name: "Anakin Skywalker (Ghost)" },
    { id: 8, name: "Luke Skywalker (Pilot)" },
    { id: 9, name: "Luke Skywalker (Dagobah)" },
    { id: 10, name: "Luke Skywalker (Jedi)" },
    { id: 11, name: "Han Solo (Skiff)" },
    { id: 12, name: "Rebel Pilot" },
    { id: 13, name: "Snowtrooper" },
    { id: 14, name: "Lobot" },
    { id: 15, name: "Bespin Guard" },
    { id: 16, name: "The Emperor" },
    { id: 17, name: "IG-88" },
    { id: 18, name: "Ben Kenobi (Ghost)" },
    { id: 19, name: "Yoda (Ghost)" },
    { id: 20, name: "Luke Skywalker (Bespin)" },
    { id: 21, name: "Princess Leia (Bespin)" },
    { id: 22, name: "Jar Jar Binks" },
    { id: 23, name: "Princess Leia (Slave)" },
    { id: 24, name: "Princess Leia (Prisoner)" },
    { id: 25, name: "Bib Fortuna" },
    { id: 26, name: "Palace Guard" },
    { id: 27, name: "Skiff Guard" },
    { id: 28, name: "Dengar" },
    { id: 29, name: "4-LOM" },
    { id: 30, name: "R2-Q5" },
    { id: 31, name: "Gungan Warrior" },
    { id: 32, name: "Lando Calrissian" },
    { id: 33, name: "Princess Leia (Boushh)" },
    { id: 34, name: "Princess Leia (Endor)" },
    { id: 35, name: "Wicket" },
    { id: 36, name: "Gamorrean Guard" },
    { id: 37, name: "R4-P17" },
    { id: 38, name: "Bossk" },
    { id: 39, name: "Boba Fett" },
    { id: 40, name: "Anakin Skywalker (Padawan)" },
    { id: 41, name: "Indiania Jones" },

    { id: 44, name: "Lando (Palace Guard)" },
    { id: 45, name: "Luke Skywalker (Endor)" },
    { id: 46, name: "Darth Vader" },
    { id: 47, name: "Queen Amidala" },
    { id: 48, name: "Princess Leia (Boushh)" },
    { id: 49, name: "Unknown" },
    { id: 50, name: "Rancor" },
    { id: 51, name: "ASP Droid" },
    { id: 52, name: "R1-G4" },
    { id: 53, name: "Chancellor Palpatine" },
    { id: 54, name: "Chewbacca" },
    { id: 55, name: "Ben Kenobi" },
    { id: 56, name: "Han Solo (Endor)" },
    { id: 57, name: "Gonk Droid" },
    { id: 58, name: "Battle Droid (Security)" },
    { id: 59, name: "Droideka" },
    { id: 60, name: "Scout Trooper" },
    { id: 61, name: "Padmé (Geonosis) / Padmé (Clawed)" },
    { id: 62, name: "Droid 2" },
    { id: 63, name: "Mace Windu" },
    { id: 64, name: "Obi-Wan Kenobi (Episode III)" },
    { id: 65, name: "Princess Leia" },
    { id: 66, name: "Captain Antilles" },
    { id: 67, name: "Han Solo (Stormtrooper)" },
    { id: 68, name: "PK Droid" },
    { id: 69, name: "Battle Droid" },
    { id: 70, name: "Captain Tarpals" },
    { id: 71, name: "Pit Droid" },
    { id: 72, name: "Wampa" },
    { id: 73, name: "Buzz Droid" },

    { id: 75, name: "Anakin Skywalker (Jedi)" },
    { id: 76, name: "Obi-Wan Kenobi" },
    { id: 77, name: "Rebel Friend" },
    { id: 78, name: "Luke Skywalker (Stormtrooper)" },
    { id: 79, name: "TC-14" },
    { id: 80, name: "Battle Droid (Commander)" },
    { id: 81, name: "Boss Nass" },
    { id: 82, name: "Watto" },
    { id: 83, name: "Zam Wesell" },
    { id: 84, name: "Treadwell Droid" },
    { id: 85, name: "C-3PO" },
    { id: 86, name: "Yoda" },
    { id: 87, name: "Commander Cody" },
    { id: 88, name: "Luke Skywalker (Tatooine)" },
    { id: 89, name: "Han Solo" },
    { id: 90, name: "Han Solo (Hoth)" },
    { id: 91, name: "Princess Leia (Hoth)" },
    { id: 92, name: "Royal Guard" },
    { id: 93, name: "Padmé" },
    { id: 94, name: "Darth Maul" },
    { id: 95, name: "Captain Panaka" },
    { id: 96, name: "Dexter Jettster" },
    { id: 97, name: "Clone" },
    { id: 98, name: "Geonosian" },
    { id: 99, name: "Super Battle Droid" },
    { id: 100, name: "Padmé (Battl" },
    { id: 101, name: "Aayla Secura" },
    { id: 102, name: "R2-D2" },
    { id: 103, name: "Clone (Episode III, Pilot)" },
    { id: 104, name: "Imperial Shuttle Pilot" },
    { id: 105, name: "Sandtrooper" },
    { id: 106, name: "Imperial Spy" },
    { id: 107, name: "Han Solo (Hood)" },
    { id: 108, name: "Lama Su" },
    { id: 109, name: "Battle Droid (Geonosis)" },
    { id: 110, name: "Boba Fett (Boy)" },
    { id: 111, name: "Ki-Adi Mundi" },
    { id: 112, name: "Plo Koon" },
    { id: 113, name: "General Grievous" },
    { id: 114, name: "Clone (Episode III, Swamp)" },
    { id: 115, name: "Disguised Clone" },
    { id: 116, name: "Tusken Raider" },
    { id: 117, name: "Beach Trooper" },
    { id: 118, name: "Imperial Officer" },
    { id: 120, name: "Taun We" },
    { id: 121, name: "Luminara" },
    { id: 122, name: "Kit Fisto" },
    { id: 123, name: "Count Dooku" },
    { id: 124, name: "Wookiee" },
    { id: 125, name: "Clone (Episode III, Walker)" },
    { id: 126, name: "Rebel Trooper" },
    { id: 127, name: "Jawa" },
    { id: 128, name: "Death Star Trooper" },
    { id: 129, name: "Grand Moff Tarkin" },
    { id: 132, name: "Jango Fett" },
    { id: 133, name: "Shaak Ti" },
    { id: 134, name: "Grievous' Bodyguard" },
    { id: 135, name: "Clone (Episode III)" },
    { id: 136, name: "Mace Windu (Episode III)" },
    { id: 137, name: "Stormtrooper" },
    { id: 138, name: "Anakin Skywalker (Boy)" },
    { id: 139, name: "Greedo" },
    { id: 140, name: "TIE Fighter Pilot" },
    { id: 141, name: "Rebel Trooper (Hoth)" },
    { id: 43, name: "Womp Rat" },
    { id: 42, name: "STRANGER 1" },
    { id: 74, name: "" }
];
